## Training ##
max-samples-training: 10000
#input-training: ../data/input_train
#label-training: ../data/label_train
input-training: nuscenes
label-training: nuscenes
model: model.py
epochs: 100
batch-size: 5
learning-rate: 1e-4
save-interval: 1
output-dir: output

## Evaluation and Prediction ##
# model-weights:
# model-weights-epoch:
store-input-point-clouds: True
store-naive-ogms: True

## Evaluation ##
max-samples-validation: 1000
#input-validation: ../data/input_valid
#label-validation: ../data/label_valid
input-validation: nuscenes
label-validation: nuscenes
store-labels: True

## Prediction ##
max-samples-testing: 10000
input-testing: nuscenes
label-testing: nuscenes
# prediction-dir:

## Model Parameters ##
min-point-distance: 3.0
intensity-threshold: 100
max-points-per-pillar: 100
max-pillars: 10000
number-features: 9
number-channels: 64
y-min: -28.16
y-max: 28.16
x-min: -40.96
x-max: 40.96
z-min: -3.0
z-max: 1.0
step-x-size: 0.16
step-y-size: 0.16
label-resize-x: 256
label-resize-y: 176
